deployments:
- name: null
  version: null
  tags: []
  description: null
  schedule: {}
  flow_name: null
  entrypoint: null
  parameters: {"lat": 22, "long": 50}
  work_pool:
    name: null
    work_queue_name: null
    job_variables: {}
